apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo
  labels:
    app: docker-demo
spec:
  selector:
    matchLabels:
      app: docker-demo
  replicas: 2
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
      - name: docker-demo
        image: dmaumenee/docker-demo:1.0
        ports:
        - containerPort: 8080
          name: docker-demo
        env:
        - name: TITLE
          value: "Kubernetes Docker Demo"
        - name: SHOW_VERSION
          value: "true"